# Generated by Django 3.2.12 on 2024-11-06 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='usuarios',
            field=models.ManyToManyField(blank=True, null=True, related_name='empresas', to='home.Profile', verbose_name='Usuários'),
        ),
    ]
