# Generated by Django 3.2.12 on 2024-11-07 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_empresa_usuarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='proprietario',
            field=models.CharField(max_length=100, verbose_name='Nome proprietário'),
        ),
    ]
